### ISSUE TITLE
Drug search interaction results show gene claim ID instead of gene group ID

### ISSUE THREAD

**Issue by obigriffith** [genome/dgi-db#51]
To be consistent with gene-based interaction search results I think the gene column in drug-based interaction search results should link to the gene group, not individual gene claim records.

**Comment by ahwagner** [comment]
I think this would be a good change. 

In the spirit of consistency, I think we should also update the old gene-based interaction search results drug column to link to the drug group, not individual drug claim records.

**Comment by acoffman** [comment]
Agreed! We were never totally satisfied with our ability to group drugs which is why we really only dealt with Gene Groups but linked to Drug Claims. With Alex's improvements, it seems possible that we can move to using both Drug Groups and Gene Groups. Of course that gets us into territory that we've talked about quite a bit over the years but never implemented: Interaction Groups. Ultimately, if we're grouping Genes and Drugs, and we have a bunch of interactions all saying that a drug inhibits a gene, then we should collapse that down to a single "interaction group." That's fairly forward looking though...

**Comment by ahwagner** [comment]
After looking this over more, @malachig and I decided that it would be best to make interaction results from gene queries display drug claims and gene groups, while interaction results from drug queries will display drug groups and gene groups. When we can better group drugs (we're still at only about 85%), we will reinvestigate doing drug groups <-> gene groups in gene search context. This was implemented in #61.
